name: Update Table of Contents

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  update-toc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate Table of Contents
        uses: Sceleratis/markdown-table-of-contents-generator-action@v1.0.2
        with:
          table-file: 'README.md'
          # Add any other inputs you want to customize
      
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Table of Contents" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}