name: Update Example Action File

on:
  release:
    types: [published]

jobs:
  update-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update example file
        run: |
          VERSION="${{ github.ref_name }}"
          sed -i 's/Sceleratis\/markdown-table-of-contents-generator-action@v[0-9.]*/Sceleratis\/markdown-table-of-contents-generator-action@'${VERSION}'/g' update-toc.yml
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add example-workflow.yml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update example to use version ${VERSION}" && git push)