name: Update Table of Contents Action Target Version

on:
    release:
      types: [published, edited]
    workflow_dispatch:
      inputs:
        version:
          description: 'Version to update to (e.g., v1.0.1)'
          required: true
  
  jobs:
    update-example:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
            token: ${{ secrets.WORKFLOW_FULL_ACCESS_PAT }}
  
        - name: Set version
          run: |
            if [ "${{ github.event_name }}" = "release" ]; then
              echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
            else
              echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
            fi
  
        - name: Debug information
          run: |
            echo "github.ref: ${{ github.ref }}"
            echo "github.ref_name: ${{ github.ref_name }}"
            echo "github.event_name: ${{ github.event_name }}"
            echo "VERSION: ${{ env.VERSION }}"
  
        - name: Update update-toc.yml to target latest version
          run: |
            echo "Updating to version: ${{ env.VERSION }}"
            sed -i 's/Sceleratis\/markdown-table-of-contents-generator-action@[^"'\''[:space:]]*/Sceleratis\/markdown-table-of-contents-generator-action@'"${{ env.VERSION }}"'/g' .github/workflows/update-toc.yml
            echo "File contents after update:"
            cat .github/workflows/update-toc.yml
  
        - name: Commit and push if changed
          run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add .github/workflows/update-toc.yml
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Update Table of Contents to target version ${{ env.VERSION }}"
              git push
            fi